// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

med_transport_init()
{
    var_0 = scripts\cp_mp\vehicles\vehicle::vehicle_getleveldataforvehicle( "medium_transport", 1 );
    var_0.destroycallback = ::med_transport_explode;
    med_transport_initoccupancy();
    med_transport_initinteract();
    _id_11BAA();
    _id_11BA9();
    med_transport_initfx();

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "medium_transport", "init" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "medium_transport", "init" ) ]]();

    med_transport_initspawning();
    med_transport_initlate();
}

med_transport_initlate()
{
    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "medium_transport", "initLate" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "medium_transport", "initLate" ) ]]();
}

med_transport_initoccupancy()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforvehicle( "medium_transport", 1 );
    var_0.enterendcallback = ::med_transport_enterend;
    var_0.exitstartcallback = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_exitstartcallback;
    var_0.exitendcallback = ::med_transport_exitend;
    var_0.restrictions = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getcombatcabpassengerrestrictions();
    var_0.exitextents["front"] = 115;
    var_0.exitextents["back"] = 115;
    var_0.exitextents["left"] = 53;
    var_0.exitextents["right"] = 53;
    var_0.exitextents["top"] = 103;
    var_0.exitextents["bottom"] = 0;
    var_1 = "front";
    var_0.exitoffsets[var_1] = ( 80, 0, 70 );
    var_0.exitdirections[var_1] = "front";
    var_1 = "back_left";
    var_0.exitoffsets[var_1] = ( -85, 22, 89 );
    var_0.exitdirections[var_1] = "back";
    var_1 = "back_right";
    var_0.exitoffsets[var_1] = ( -85, -22, 89 );
    var_0.exitdirections[var_1] = "back";
    var_2 = [];
    var_2[var_2.size] = "driver";
    var_2[var_2.size] = "front_right_rear";
    var_2[var_2.size] = "back_right_rear";
    var_2[var_2.size] = "back_left_rear";
    var_2[var_2.size] = "front_left_rear";
    var_2[var_2.size] = "front_left";
    var_3 = "driver";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "back_right_rear", "back_right", "front_left", "front" ];
    var_0.exitoffsets[var_3] = ( 15, -20, 76 );
    var_0.exitdirections[var_3] = "right";
    var_4.restrictions = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getdriverrestrictions();
    var_4.damagemodifier = 0.5;
    var_4.animtag = "tag_seat_0";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4.spawnpriority = 10;
    var_4._id_12023 = "ping_vehicle_driver";
    var_3 = "front_left";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "back_left_rear", "back_left", "driver", "front" ];
    var_0.exitoffsets[var_3] = ( 15, 20, 76 );
    var_0.exitdirections[var_3] = "left";
    var_4.animtag = "tag_seat_1";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4._id_12023 = "ping_vehicle_rider";
    var_3 = "front_left_rear";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "back_left_rear", "back_left", "front_right_rear", "front" ];
    var_0.exitoffsets[var_3] = ( -25, 22, 89 );
    var_0.exitdirections[var_3] = "left";
    var_4.animtag = "tag_seat_2";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4._id_12023 = "ping_vehicle_rider";
    var_3 = "front_right_rear";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "back_right_rear", "back_right", "front_left_rear", "front" ];
    var_0.exitoffsets[var_3] = ( -25, -22, 89 );
    var_0.exitdirections[var_3] = "right";
    var_4.animtag = "tag_seat_5";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4._id_12023 = "ping_vehicle_rider";
    var_3 = "back_left_rear";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "front_left", "back_left", "back_right_rear", "front" ];
    var_0.exitoffsets[var_3] = ( -51, 22, 89 );
    var_0.exitdirections[var_3] = "left";
    var_4.animtag = "tag_seat_3";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4._id_12023 = "ping_vehicle_rider";
    var_3 = "back_right_rear";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "medium_transport", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ var_3, "driver", "back_right", "back_left_rear", "front" ];
    var_0.exitoffsets[var_3] = ( -51, -22, 89 );
    var_0.exitdirections[var_3] = "right";
    var_4.animtag = "tag_seat_6";
    var_4.exittag = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animtagtoexittag( var_4.animtag );
    var_4._id_12023 = "ping_vehicle_rider";
}

med_transport_initinteract()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_interact::vehicle_interact_getleveldataforvehicle( "medium_transport", 1 );
    var_0.seatenterarrays["driver"] = [ "driver" ];
    var_0.seatenterarrays["front_left"] = [ "front_left" ];
    var_0.seatenterarrays["front_left_rear"] = [ "front_left_rear" ];
    var_0.seatenterarrays["front_right_rear"] = [ "front_right_rear" ];
    var_0.seatenterarrays["back_left_rear"] = [ "back_left_rear" ];
    var_0.seatenterarrays["back_right_rear"] = [ "back_right_rear" ];
}

_id_11BAA()
{
    var_0 = scripts\cp_mp\utility\vehicle_omnvar_utility::_id_1427E( "medium_transport", 1 );
    var_0.id = 11;
    var_0.seatids["driver"] = 0;
    var_0.seatids["front_left"] = 1;
    var_0.seatids["front_left_rear"] = 2;
    var_0.seatids["front_right_rear"] = 3;
    var_0.seatids["back_left_rear"] = 4;
    var_0.seatids["back_right_rear"] = 5;
}

_id_11BA9()
{
    scripts\cp_mp\vehicles\vehicle_damage::_id_1416C( "medium_transport", 2000 );
    var_0 = scripts\cp_mp\vehicles\vehicle_damage::vehicle_damage_getleveldataforvehicle( "medium_transport" );
    var_0.class = "medium_heavy";
    scripts\cp_mp\vehicles\vehicle_damage::_id_1413D( "medium_transport" );
    scripts\cp_mp\vehicles\vehicle_damage::_id_14178( "medium_transport", 13 );
    scripts\cp_mp\vehicles\vehicle_damage::_id_14171( "medium_transport", ::med_transport_deathcallback );
    scripts\cp_mp\vehicles\vehicle_damage::_id_1417B( "med_transport_mp", 3 );
}

med_transport_initfx()
{
    level._effect["med_transport_explode"] = loadfx( "vfx/iw8/veh/scriptables/vfx_veh_explosion_sedan.vfx" );
}

med_transport_create( var_0, var_1 )
{
    if ( !isdefined( var_0.angles ) )
        var_0.angles = ( 0, 0, 0 );

    var_0.modelname = "veh8_mil_lnd_asierra_physics_mp";
    var_0.targetname = "medium_transport";
    var_0.vehicletype = "asierra_physics_mp";
    var_2 = scripts\cp_mp\vehicles\vehicle_tracking::_spawnvehicle( var_0, var_1 );

    if ( !isdefined( var_2 ) )
        return undefined;

    scripts\cp_mp\vehicles\vehicle::_id_14138( var_2, "medium_transport", var_0 );
    var_2.objweapon = getcompleteweaponname( "med_transport_mp" );
    _calloutmarkerping_predicted_timeout::_id_1412B( var_2 );
    scripts\cp_mp\vehicles\vehicle::_id_14139( var_2, var_0 );
    thread scripts\cp_mp\vehicles\vehicle::vehicle_watchflipped( var_2, undefined, scripts\cp_mp\vehicles\vehicle::vehicle_flippedendcallback );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "medium_transport", "create" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "medium_transport", "create" ) ]]( var_2 );

    return var_2;
}

med_transport_explode( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
    {
        var_0 = spawnstruct();
        var_0.inflictor = self;
        var_0.objweapon = "med_transport_mp";
        var_0.meansofdeath = "MOD_EXPLOSIVE";
    }

    scripts\cp_mp\vehicles\vehicle_damage::_id_14162( var_0 );
    scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_killoccupants( self, var_0 );
    scripts\cp_mp\vehicles\vehicle_damage::vehicle_damage_clearvisuals( undefined, undefined, 1 );
    thread med_transport_deletenextframe();

    if ( !istrue( level.suppressvehicleexplosion ) )
    {
        var_2 = self gettagorigin( "tag_origin" );
        var_3 = scripts\engine\utility::ter_op( isdefined( var_0.attacker ) && isent( var_0.attacker ), var_0.attacker, self );
        self radiusdamage( var_2, 256, 140, 70, var_3, "MOD_EXPLOSIVE", "med_transport_mp" );
        playfx( scripts\engine\utility::getfx( "med_transport_explode" ), var_2, anglestoforward( self.angles ), anglestoup( self.angles ) );
        playsoundatpos( var_2, "car_explode" );
        earthquake( 0.4, 800, var_2, 0.7 );
        playrumbleonposition( "grenade_rumble", var_2 );
        physicsexplosionsphere( var_2, 500, 200, 1 );
    }
}

med_transport_deletenextframe()
{
    scripts\cp_mp\vehicles\vehicle::_id_14185( self );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "medium_transport", "delete" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "medium_transport", "delete" ) ]]( self );

    waitframe();
    scripts\cp_mp\vehicles\vehicle::_id_14186( self );
}

med_transport_deathcallback( var_0 )
{
    thread med_transport_explode( var_0 );
    return 1;
}

med_transport_enterend( var_0, var_1, var_2, var_3, var_4 )
{
    if ( istrue( var_4.success ) )
        med_transport_enterendinternal( var_0, var_1, var_2, var_3, var_4 );
}

med_transport_enterendinternal( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_1 == "driver" )
    {
        var_0 setotherent( var_3 );
        var_0 setentityowner( var_3 );
        var_3 controlslinkto( var_0 );
    }

    var_3 thread scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animateplayer( var_0, var_1, var_2 );
    scripts\cp_mp\utility\vehicle_omnvar_utility::vehomn_updateomnvarsonseatenter( var_0, var_2, var_1, var_3 );
}

med_transport_exitend( var_0, var_1, var_2, var_3, var_4 )
{
    if ( istrue( var_4.success ) )
        med_transport_exitendinternal( var_0, var_1, var_2, var_3, var_4 );
}

med_transport_exitendinternal( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_1 == "driver" )
    {
        var_0 setotherent( undefined );
        var_0 setentityowner( undefined );

        if ( !istrue( var_4.playerdisconnect ) )
            var_3 controlsunlink();
    }

    if ( !istrue( var_4.playerdisconnect ) )
    {
        var_3 scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_stopanimatingplayer();
        var_5 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_moveplayertoexit( var_3, var_2, var_4 );

        if ( !var_5 )
        {
            if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "vehicle_occupancy", "handleSuicideFromVehicles" ) )
                [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "vehicle_occupancy", "handleSuicideFromVehicles" ) ]]( var_3 );
            else
                var_3 suicide();
        }
    }

    scripts\cp_mp\utility\vehicle_omnvar_utility::vehomn_updateomnvarsonseatexit( var_0, var_1, var_2, var_3 );
}

med_transport_initspawning()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_getleveldataforvehicle( "medium_transport", 1 );
    var_0.maxinstancecount = 30;
    var_0.priority = 50;
    var_0.getspawnstructscallback = ::med_transport_getspawnstructscallback;
    var_0.spawncallback = scripts\cp_mp\utility\script_utility::getsharedfunc( "medium_transport", "spawnCallback" );
    var_0.clearancecheckradius = 110;
    var_0.clearancecheckheight = 110;
    var_0.clearancecheckminradius = 110;
}

med_transport_getspawnstructscallback()
{
    var_0 = scripts\engine\utility::getstructarray( "mediumtransport_spawn", "targetname" );

    if ( var_0.size > 0 )
    {
        var_0 = scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_removespawnstructswithflag( var_0, 1 );

        if ( var_0.size > 1 )
            var_0 = scripts\engine\utility::array_randomize( var_0 );
    }

    return var_0;
}
